package com.dreammaster.gthandler;

import com.dreammaster.item.*;
import cpw.mods.fml.common.Loader;
import gregtech.api.enums.*;
import gregtech.api.enums.ItemList;
import gregtech.api.util.GT_ModHandler;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

public class GT_CraftingRecipeLoader extends gregtech.loaders.postload.GT_CraftingRecipeLoader
        implements Runnable {
    public void run() {

        GT_ModHandler.addCraftingRecipe(CustomItemList.RawOrbTier1.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"XTX", "POP", "PPP", Character.valueOf('X'), OrePrefixes.screw.get(Materials.Aluminium), Character.valueOf('T'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('P'), OrePrefixes.plate.get(Materials.AnnealedCopper), Character.valueOf('O'), CustomItemList.ReinforcedGlassLense.get(1L, new Object[0])});
        GT_ModHandler.addCraftingRecipe(CustomItemList.RawOrbTier2.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"XTX", "POP", "PPP", Character.valueOf('X'), OrePrefixes.screw.get(Materials.StainlessSteel), Character.valueOf('T'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('P'), OrePrefixes.plate.get(Materials.RoseGold), Character.valueOf('O'), CustomItemList.ReinforcedGlassLense.get(1L, new Object[0])});
        GT_ModHandler.addCraftingRecipe(CustomItemList.RawOrbTier3.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"XTX", "POP", "PPP", Character.valueOf('X'), OrePrefixes.screw.get(Materials.Titanium), Character.valueOf('T'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('P'), OrePrefixes.plate.get(Materials.PulsatingIron), Character.valueOf('O'), CustomItemList.ReinforcedGlassLense.get(1L, new Object[0])});
        GT_ModHandler.addCraftingRecipe(CustomItemList.RawOrbTier4.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"XTX", "POP", "PPP", Character.valueOf('X'), OrePrefixes.screw.get(Materials.TungstenSteel), Character.valueOf('T'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('P'), OrePrefixes.plate.get(Materials.EnergeticAlloy), Character.valueOf('O'), CustomItemList.ReinforcedGlassLense.get(1L, new Object[0])});
        GT_ModHandler.addCraftingRecipe(CustomItemList.RawOrbTier5.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"XTX", "POP", "PPP", Character.valueOf('X'), OrePrefixes.screw.get(Materials.Chrome), Character.valueOf('T'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('P'), OrePrefixes.plate.get(Materials.FierySteel), Character.valueOf('O'), CustomItemList.ReinforcedGlassLense.get(1L, new Object[0])});
        GT_ModHandler.addCraftingRecipe(CustomItemList.RawOrbTier6.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"XTX", "POP", "PPP", Character.valueOf('X'), OrePrefixes.screw.get(Materials.Iridium), Character.valueOf('T'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('P'), OrePrefixes.plate.get(Materials.Plutonium241), Character.valueOf('O'), CustomItemList.ReinforcedGlassLense.get(1L, new Object[0])});

        GT_ModHandler.addCraftingRecipe(CustomItemList.WoodenCasing.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"SSS", "UCU", "SDS", Character.valueOf('S'), OrePrefixes.slab.get(Materials.Wood), Character.valueOf('D'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('U'), OrePrefixes.screw.get(Materials.Iron), Character.valueOf('C'), OrePrefixes.frameGt.get(Materials.Wood)});

        GT_ModHandler.removeRecipeByOutput(GT_ModHandler.getModItem("Railcraft", "machine.beta", 1L, 3));
        GT_ModHandler.removeRecipeByOutput(GT_ModHandler.getModItem("Railcraft", "machine.beta", 1L, 4));
        GT_ModHandler.addCraftingRecipe(GT_ModHandler.getModItem("Railcraft", "machine.beta", 1L, 3), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"III", "SHS", "III", Character.valueOf('H'), ToolDictNames.craftingToolHardHammer, Character.valueOf('I'), ItemList.IC2_Item_Casing_Iron, Character.valueOf('S'), OrePrefixes.screw.get(Materials.AnyIron)});
        GT_ModHandler.addCraftingRecipe(GT_ModHandler.getModItem("Railcraft", "machine.beta", 1L, 4), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"LLL", "SHS", "LLL", Character.valueOf('H'), ToolDictNames.craftingToolHardHammer, Character.valueOf('L'), ItemList.IC2_Item_Casing_Steel, Character.valueOf('S'), OrePrefixes.screw.get(Materials.Steel)});

        GT_ModHandler.addShapelessCraftingRecipe(GT_ModHandler.getIC2Item("miningPipe", 1L), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{GT_ModHandler.getIC2Item("miningPipeTip", 1L)});

        GT_ModHandler.addCraftingRecipe(GT_ModHandler.getModItem("GalaxySpace", "item.ModuleSmallCanister", 1L, 0), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"PPP", "PCP", "PPP", Character.valueOf('P'), OrePrefixes.compressed.get(Materials.Steel), Character.valueOf('C'), GT_ModHandler.getModItem("GalacticraftCore", "item.oilCanisterPartial", 1L, 1001)});
        GT_ModHandler.addCraftingRecipe(GT_ModHandler.getModItem("GalaxySpace", "item.ModuleSmallFuelCanister", 1L, 0), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"SRS", "TCD", "SHS", Character.valueOf('S'), OrePrefixes.screw.get(Materials.StainlessSteel), Character.valueOf('R'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('T'), GT_ModHandler.getModItem("GalaxySpace", "item.CompressedDualBronze", 1L, 0), Character.valueOf('D'), GT_ModHandler.getModItem("GalaxySpace", "item.CompressedDualAluminium", 1L, 0), Character.valueOf('C'), GT_ModHandler.getModItem("GalaxySpace", "item.ModuleSmallCanister", 1L, 0), Character.valueOf('H'), ToolDictNames.craftingToolHardHammer});
        GT_ModHandler.addCraftingRecipe(CustomItemList.MediumFuelCanister.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"SRS", "TCD", "SHS", Character.valueOf('S'), OrePrefixes.screw.get(Materials.Titanium), Character.valueOf('R'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('T'), CustomItemList.TitaniumDualCompressedPlates.get(1, new Object[0]), Character.valueOf('D'), CustomItemList.DeshDualCompressedPlates.get(1, new Object[0]), Character.valueOf('C'), GT_ModHandler.getModItem("GalaxySpace", "item.ModuleSmallFuelCanister", 1L, 0), Character.valueOf('H'), ToolDictNames.craftingToolHardHammer});
        GT_ModHandler.addCraftingRecipe(CustomItemList.LargeFuelCanister.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"SRS", "TCD", "SHS", Character.valueOf('S'), OrePrefixes.screw.get(Materials.Chrome), Character.valueOf('R'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('T'), CustomItemList.QuantinumDualCompressedPlates.get(1, new Object[0]), Character.valueOf('D'), CustomItemList.IceDualCompressedPlates.get(1, new Object[0]), Character.valueOf('C'), CustomItemList.MediumFuelCanister.get(1, new Object[0]), Character.valueOf('H'), ToolDictNames.craftingToolHardHammer});
        GT_ModHandler.addCraftingRecipe(CustomItemList.ExtraLargeFuelCanister.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"SRS", "TCD", "SHS", Character.valueOf('S'), OrePrefixes.screw.get(Materials.Iridium), Character.valueOf('R'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('T'), CustomItemList.MytrylDualCompressedPlates.get(1, new Object[0]), Character.valueOf('D'), CustomItemList.MysteriousCrystalDualCompressedPlates.get(1, new Object[0]), Character.valueOf('C'), CustomItemList.LargeFuelCanister.get(1, new Object[0]), Character.valueOf('H'), ToolDictNames.craftingToolHardHammer});
        GT_ModHandler.addCraftingRecipe(CustomItemList.HeavyDutyRocketEngineTier3.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"BPB", "PPP", "EPE", Character.valueOf('B'), CustomItemList.Tier2Booster.get(1, new Object[0]), Character.valueOf('P'), CustomItemList.HeavyDutyPlateTier5.get(1, new Object[0]), Character.valueOf('E'), GT_ModHandler.getModItem("GalacticraftMars", "item.itemBasicAsteroids", 1L, 1)});
        GT_ModHandler.addCraftingRecipe(CustomItemList.HeavyDutyRocketEngineTier4.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"BPB", "PPP", "EPE", Character.valueOf('B'), CustomItemList.Tier3Booster.get(1, new Object[0]), Character.valueOf('P'), CustomItemList.HeavyDutyPlateTier7.get(1, new Object[0]), Character.valueOf('E'), CustomItemList.HeavyDutyRocketEngineTier3.get(1, new Object[0])});
        GT_ModHandler.addCraftingRecipe(CustomItemList.HeavyDutyNoseConeTier3.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"SNH", "CPC", "PPP", Character.valueOf('N'), GT_ModHandler.getModItem("GalacticraftMars", "item.heavyNoseCone", 1L, 0), Character.valueOf('P'), CustomItemList.HeavyDutyPlateTier5.get(1, new Object[0]), Character.valueOf('C'), OrePrefixes.screw.get(Materials.TungstenSteel), Character.valueOf('S'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('H'), ToolDictNames.craftingToolHardHammer});
        GT_ModHandler.addCraftingRecipe(CustomItemList.HeavyDutyNoseConeTier4.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"SNH", "CPC", "PPP", Character.valueOf('N'), CustomItemList.HeavyDutyNoseConeTier3.get(1, new Object[0]), Character.valueOf('P'), CustomItemList.HeavyDutyPlateTier7.get(1, new Object[0]), Character.valueOf('C'), OrePrefixes.screw.get(Materials.NaquadahAlloy), Character.valueOf('S'), ToolDictNames.craftingToolScrewdriver, Character.valueOf('H'), ToolDictNames.craftingToolHardHammer});
        GT_ModHandler.addCraftingRecipe(CustomItemList.HeavyDutyRocketFinsTier3.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"HPF", "QPQ", "QSQ", Character.valueOf('P'), CustomItemList.HeavyDutyPlateTier4.get(1, new Object[0]), Character.valueOf('Q'), CustomItemList.HeavyDutyPlateTier5.get(1, new Object[0]), Character.valueOf('S'), GT_ModHandler.getModItem("GalaxySpace", "item.CompressedSDHD120", 1L, 0) , Character.valueOf('F'), ToolDictNames.craftingToolFile, Character.valueOf('H'), ToolDictNames.craftingToolHardHammer});
        GT_ModHandler.addCraftingRecipe(CustomItemList.HeavyDutyRocketFinsTier4.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"HPF", "QPQ", "QSQ", Character.valueOf('P'), CustomItemList.HeavyDutyPlateTier6.get(1, new Object[0]), Character.valueOf('Q'), CustomItemList.HeavyDutyPlateTier7.get(1, new Object[0]), Character.valueOf('S'), GT_ModHandler.getModItem("GalaxySpace", "item.CompressedSDHD120", 1L, 0), Character.valueOf('F'), ToolDictNames.craftingToolFile, Character.valueOf('H'), ToolDictNames.craftingToolHardHammer});
        GT_ModHandler.addCraftingRecipe(CustomItemList.Tier2Booster.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"LLL", "PBP", "PVP", Character.valueOf('L'), CustomItemList.LedoxCompressedPlate.get(1, new Object[0]), Character.valueOf('P'), GT_ModHandler.getModItem("GalacticraftMars", "item.itemBasicAsteroids", 1L, 0), Character.valueOf('B'), GT_ModHandler.getModItem("GalacticraftCore", "item.engine", 1L, 1), Character.valueOf('V'), GT_ModHandler.getModItem("GalaxySpace", "item.CompressedSDHD120", 1L, 0)});
        GT_ModHandler.addCraftingRecipe(CustomItemList.Tier3Booster.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"LLL", "PBP", "PVP", Character.valueOf('L'), CustomItemList.MytrylCompressedPlate.get(1, new Object[0]), Character.valueOf('P'), CustomItemList.HeavyDutyPlateTier5.get(1, new Object[0]), Character.valueOf('B'), CustomItemList.Tier2Booster.get(1, new Object[0]), Character.valueOf('V'), GT_ModHandler.getModItem("GalaxySpace", "item.CompressedSDHD120", 1L, 0)});
        GT_ModHandler.addCraftingRecipe(CustomItemList.Tier4Booster.get(1L, new Object[0]), GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE, new Object[]{"LLL", "PBP", "PVP", Character.valueOf('L'), CustomItemList.BlackPlutoniumCompressedPlate.get(1, new Object[0]), Character.valueOf('P'), CustomItemList.HeavyDutyPlateTier7.get(1, new Object[0]), Character.valueOf('B'), CustomItemList.Tier3Booster.get(1, new Object[0]), Character.valueOf('V'), GT_ModHandler.getModItem("GalaxySpace", "item.CompressedSDHD120", 1L, 0)});

        GT_ModHandler.addCraftingRecipe(ItemList.Teleporter.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"CPC", "PMP", "BIB", 'M', ItemList.Hull_LuV, 'B', ItemList.Tool_DataOrb, 'C', CustomItemList.PikoCircuit.get(1, new Object[0]), 'P', ItemList.Field_Generator_UV, 'I', GT_ModHandler.getModItem("Avaritia", "Resource_Block", 1L, 1)});

        GT_ModHandler.addCraftingRecipe(CustomItemList.IndustryFrame.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"PPP", "SBS", "SSS", 'P', OrePrefixes.plate.get(Materials.Palladium), 'S', OrePrefixes.stick.get(Materials.Osmium), 'B', CustomItemList.IridiumBars.get(1, new Object[0])});

        GT_ModHandler.addCraftingRecipe(ItemList.Generator_Naquadah_Mark_I.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"UCU", "FMF", "WCW", Character.valueOf('M'), ItemList.Hull_EV, Character.valueOf('F'), ItemList.Field_Generator_EV, Character.valueOf('C'), OrePrefixes.circuit.get(Materials.Master), Character.valueOf('W'), OrePrefixes.cableGt04.get(Materials.Aluminium), Character.valueOf('U'), OrePrefixes.stick.get(Materials.Uranium235)});
        GT_ModHandler.addCraftingRecipe(ItemList.Generator_Naquadah_Mark_II.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"PCP", "FMF", "WCW", Character.valueOf('M'), ItemList.Hull_IV, Character.valueOf('F'), ItemList.Field_Generator_IV, Character.valueOf('C'), CustomItemList.HighEnergyFlowCircuit, Character.valueOf('W'), OrePrefixes.cableGt04.get(Materials.Tungsten), Character.valueOf('P'), OrePrefixes.stick.get(Materials.Plutonium241)});
        GT_ModHandler.addCraftingRecipe(ItemList.Generator_Naquadah_Mark_III.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"NCN", "FMF", "WCW", Character.valueOf('M'), ItemList.Hull_LuV, Character.valueOf('F'), ItemList.Field_Generator_LuV, Character.valueOf('C'), CustomItemList.NanoCircuit, Character.valueOf('W'), OrePrefixes.cableGt04.get(Materials.HSSG), Character.valueOf('N'), OrePrefixes.stick.get(Materials.Europium)});
        GT_ModHandler.addCraftingRecipe(ItemList.Generator_Naquadah_Mark_IV.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"NCN", "FMF", "WCW", Character.valueOf('M'), ItemList.Hull_ZPM, Character.valueOf('F'), ItemList.Field_Generator_ZPM, Character.valueOf('C'), CustomItemList.PikoCircuit, Character.valueOf('W'), OrePrefixes.cableGt04.get(Materials.Naquadah), Character.valueOf('N'), OrePrefixes.stick.get(Materials.Americium)});
        GT_ModHandler.addCraftingRecipe(ItemList.Generator_Naquadah_Mark_V.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"NCN", "FMF", "WCW", Character.valueOf('M'), ItemList.Hull_UV, Character.valueOf('F'), ItemList.Field_Generator_UV, Character.valueOf('C'), CustomItemList.QuantumCircuit, Character.valueOf('W'), OrePrefixes.cableGt04.get(Materials.ElectrumFlux), Character.valueOf('N'), OrePrefixes.stick.get(Materials.NaquadahAlloy)});

        GT_ModHandler.addCraftingRecipe(ItemList.LargeHPSteamTurbine.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"CPC", "PMP", "BPB", 'M', ItemList.Hull_IV, 'B', OrePrefixes.pipeLarge.get(Materials.TungstenSteel), 'C', CustomItemList.NanoCircuit, 'P', OrePrefixes.gearGt.get(Materials.TungstenSteel)});
        GT_ModHandler.addCraftingRecipe(ItemList.LargePlasmaTurbine.get(1L, new Object[0]), GT_ModHandler.RecipeBits.DISMANTLEABLE | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{"CPC", "PMP", "BPB", 'M', ItemList.Hull_UV, 'B', OrePrefixes.pipeHuge.get(Materials.Naquadah), 'C',  CustomItemList.PikoCircuit, 'P', OrePrefixes.gearGt.get(Materials.NaquadahAlloy)});

        if (Loader.isModLoaded("HardcoreEnderExpansion")) {
            long tBitMask = GT_ModHandler.RecipeBits.BUFFERED | GT_ModHandler.RecipeBits.NOT_REMOVABLE | GT_ModHandler.RecipeBits.REVERSIBLE | GT_ModHandler.RecipeBits.DELETE_ALL_OTHER_RECIPES_IF_SAME_NBT | GT_ModHandler.RecipeBits.DELETE_ALL_OTHER_SHAPED_RECIPES | GT_ModHandler.RecipeBits.DELETE_ALL_OTHER_NATIVE_RECIPES | GT_ModHandler.RecipeBits.ONLY_ADD_IF_THERE_IS_ANOTHER_RECIPE_FOR_IT;
            GT_ModHandler.addCraftingRecipe(GT_ModHandler.getModItem("HardcoreEnderExpansion", "altar_nexus", 1L, 0), tBitMask, new Object[]{"DED", "EDE", "DED", Character.valueOf('D'), new ItemStack(Items.diamond, 1), Character.valueOf('E'), new ItemStack(Items.ender_eye, 1),});


        }
    }
}