package com.dreammaster.item;

import net.minecraft.item.ItemStack;

import com.dreammaster.creativetab.ModTabList;
import com.dreammaster.lib.Refstrings;
import com.dreammaster.main.MainRegistry;

import eu.usrv.yamcore.items.ModItemManager;
import eu.usrv.yamcore.items.ModSimpleBaseItem;

public enum ItemList
{
    TenKCell(new ModSimpleBaseItem("TenKCell", ModTabList.ModGenericTab)),
    ThirtyKCell(new ModSimpleBaseItem("ThirtyKCell", ModTabList.ModGenericTab)),
    SixtyKCell(new ModSimpleBaseItem("SixtyKCell", ModTabList.ModGenericTab)),
    AluminiumBars(new ModSimpleBaseItem("AluminiumBars", ModTabList.ModGenericTab)),
    AluminiumItemCasing(new ModSimpleBaseItem("AluminiumItemCasing", ModTabList.ModGenericTab)),
    AluminiumIronPlate(new ModSimpleBaseItem("AluminiumIronPlate", ModTabList.ModGenericTab)),
    AdvancedCokeOvenBrick(new ModSimpleBaseItem("AdvancedCokeOvenBrick", ModTabList.ModGenericTab)),
    AdvancedProcessorBoard(new ModSimpleBaseItem("AdvancedProcessorBoard", ModTabList.ModCircuitsTab)),
    ArditePlate(new ModSimpleBaseItem("ArditePlate", ModTabList.ModGenericTab)),
    AsteroidsStoneDust(new ModSimpleBaseItem("AsteroidsStoneDust", ModTabList.ModGenericTab)),
    BedrockiumPlate(new ModSimpleBaseItem("BedrockiumPlate", ModTabList.ModGenericTab)),
    BioCarbonPlate(new ModSimpleBaseItem("BioCarbonPlate", ModTabList.ModGenericTab)),
    BioBall(new ModSimpleBaseItem("BioBall", ModTabList.ModGenericTab)),
    BioOrganicMesh(new ModSimpleBaseItem("BioOrganicMesh", ModTabList.ModGenericTab)),
    BioChunk(new ModSimpleBaseItem("BioChunk", ModTabList.ModGenericTab)),
    BowFletchingCast(new ModSimpleBaseItem("BowFletchingCast", ModTabList.ModGenericTab)),
    BowStringCast(new ModSimpleBaseItem("BowStringCast", ModTabList.ModGenericTab)),
    CompressedBioBall(new ModSimpleBaseItem("CompressedBioBall", ModTabList.ModGenericTab)),
    BlackPlutoniumDust(new ModSimpleBaseItem("BlackPlutoniumDust", ModTabList.ModGenericTab)),
    BlackPlutoniumPlate(new ModSimpleBaseItem("BlackPlutoniumPlate", ModTabList.ModGenericTab)),
    BlackPlutoniumDensePlate(new ModSimpleBaseItem("BlackPlutoniumDensePlate", ModTabList.ModGenericTab)),
    BlankPlatedChip(new ModSimpleBaseItem("BlankPlatedChip", ModTabList.ModCircuitsTab)),
    CallistoIceDust(new ModSimpleBaseItem("CallistoIceDust", ModTabList.ModGenericTab)),
    CallistoIceIngot(new ModSimpleBaseItem("CallistoIceIngot", ModTabList.ModGenericTab)),
    CallistoIceColdIngot(new ModSimpleBaseItem("CallistoIceColdIngot", ModTabList.ModGenericTab)),
    CallistoIcePlate(new ModSimpleBaseItem("CallistoIcePlate", ModTabList.ModGenericTab)),
    CallistoIceDensePlate(new ModSimpleBaseItem("CallistoIceDensePlate", ModTabList.ModGenericTab)),
    CallistoIceCompressedPlate(new ModSimpleBaseItem("CallistoIceCompressedPlate", ModTabList.ModGenericTab)),
    CarbonPartBoots(new ModSimpleBaseItem("CarbonPartBoots", ModTabList.ModGenericTab)),
    CarbonPartChestplate(new ModSimpleBaseItem("CarbonPartChestplate", ModTabList.ModGenericTab)),
    CarbonPartHelmet(new ModSimpleBaseItem("CarbonPartHelmet", ModTabList.ModGenericTab)),
    CarbonPartHelmetNightVision(new ModSimpleBaseItem("CarbonPartHelmetNightVision", ModTabList.ModGenericTab)),
    CarbonPartLeggings(new ModSimpleBaseItem("CarbonPartLeggings", ModTabList.ModGenericTab)),
    CarminiteChip(new ModSimpleBaseItem("CarminiteChip", ModTabList.ModThaumcraftTab)),
    CarminiteFragment(new ModSimpleBaseItem("CarminiteFragment", ModTabList.ModThaumcraftTab)),
    ChargedSilverWandCap(new ModSimpleBaseItem("ChargedSilverWandCap", ModTabList.ModThaumcraftTab)),
    ChargedThaumiumWandCap(new ModSimpleBaseItem("ChargedThaumiumWandCap", ModTabList.ModThaumcraftTab)),
    ChargedVoidWandCap(new ModSimpleBaseItem("ChargedVoidWandCap", ModTabList.ModThaumcraftTab)),
    ChargedCertusQuartzDust(new ModSimpleBaseItem("ChargedCertusQuartzDust", ModTabList.ModGenericTab)),
    ChargedCertusQuartzPlate(new ModSimpleBaseItem("ChargedCertusQuartzPlate", ModTabList.ModGenericTab)),
    ChargedCertusQuartzRod(new ModSimpleBaseItem("ChargedCertusQuartzRod", ModTabList.ModGenericTab)),
    CokeOvenBrick(new ModSimpleBaseItem("CokeOvenBrick", ModTabList.ModGenericTab)),
    ConductiveIronBars(new ModSimpleBaseItem("ConductiveIronBars", ModTabList.ModGenericTab)),
    ChromeBars(new ModSimpleBaseItem("ChromeBars", ModTabList.ModGenericTab)),
    ChromeItemCasing(new ModSimpleBaseItem("ChromeItemCasing", ModTabList.ModGenericTab)),
    ChromeIronPlate(new ModSimpleBaseItem("ChromeIronPlate", ModTabList.ModGenericTab)),
    CobbleStoneRod(new ModSimpleBaseItem("CobbleStoneRod", ModTabList.ModGenericTab)),
    CopperWandCap(new ModSimpleBaseItem("CopperWandCap", ModTabList.ModThaumcraftTab)),
    Display(new ModSimpleBaseItem("Display", ModTabList.ModCircuitsTab)),
    DiamondCoreChip(new ModSimpleBaseItem("DiamondCoreChip", ModTabList.ModCircuitsTab)),
    DiamondDrillTip(new ModSimpleBaseItem("DiamondDrillTip", ModTabList.ModGenericTab)),
    DiamondFluidCoreChip(new ModSimpleBaseItem("DiamondFluidCoreChip", ModTabList.ModCircuitsTab)),
    ElectricalSteelBars(new ModSimpleBaseItem("ElectricalSteelBars", ModTabList.ModGenericTab)),
    ElectricBoatHull(new ModSimpleBaseItem("ElectricBoatHull", ModTabList.ModGenericTab)),
    ElectrotineWire(new ModSimpleBaseItem("ElectrotineWire", ModTabList.ModGenericTab)),
    EmeraldAdvancedCoreChip(new ModSimpleBaseItem("EmeraldAdvancedCoreChip", ModTabList.ModCircuitsTab)),
    EmeraldAdvancedFluidCoreChip(new ModSimpleBaseItem("EmeraldAdvancedFluidCoreChip", ModTabList.ModCircuitsTab)),
    EmeraldHighAdvancedCoreChip(new ModSimpleBaseItem("EmeraldHighAdvancedCoreChip", ModTabList.ModCircuitsTab)),
    EnderiumBaseBars(new ModSimpleBaseItem("EnderiumBaseBars", ModTabList.ModGenericTab)),
    EnderiumBars(new ModSimpleBaseItem("EnderiumBars", ModTabList.ModGenericTab)),
    EnergeticAlloyBars(new ModSimpleBaseItem("EnergeticAlloyBars", ModTabList.ModGenericTab)),
    EngineeringProcessorFluidDiamondCore(new ModSimpleBaseItem("EngineeringProcessorFluidDiamondCore", ModTabList.ModCircuitsTab)),
    EngineeringProcessorFluidEmeraldCore(new ModSimpleBaseItem("EngineeringProcessorFluidEmeraldCore", ModTabList.ModCircuitsTab)),
    EngineeringProcessorItemAdvEmeraldCore(new ModSimpleBaseItem("EngineeringProcessorItemAdvEmeraldCore", ModTabList.ModCircuitsTab)),
    EngineeringProcessorItemEmeraldCore(new ModSimpleBaseItem("EngineeringProcessorItemEmeraldCore", ModTabList.ModCircuitsTab)),
    EngineeringProcessorItemDiamondCore(new ModSimpleBaseItem("EngineeringProcessorItemDiamondCore", ModTabList.ModCircuitsTab)),
    EngineeringProcessorSpatialPulsatingCore(new ModSimpleBaseItem("EngineeringProcessorSpatialPulsatingCore", ModTabList.ModCircuitsTab)),
    EngineCore(new ModSimpleBaseItem("EngineCore", ModTabList.ModGenericTab)),
    EngravedEnergyChip(new ModSimpleBaseItem("EngravedEnergyChip", ModTabList.ModCircuitsTab)),
    EngravedDiamondCrystalChip(new ModSimpleBaseItem("EngravedDiamondCrystalChip", ModTabList.ModCircuitsTab)),
    EngravedGoldChip(new ModSimpleBaseItem("EngravedGoldChip", ModTabList.ModCircuitsTab)),
    EngravedQuantumChip(new ModSimpleBaseItem("EngravedQuantumChip", ModTabList.ModCircuitsTab)),
    EnrichedNaquadriaSunnariumAlloy(new ModSimpleBaseItem("EnrichedNaquadriaSunnariumAlloy", ModTabList.ModGenericTab)),
    EnrichedNaquadriaNeutroniumSunnariumAlloy(new ModSimpleBaseItem("EnrichedNaquadriaNeutroniumSunnariumAlloy", ModTabList.ModGenericTab)),
    EnvironmentalCircuit(new ModSimpleBaseItem("EnvironmentalCircuit", ModTabList.ModCircuitsTab)),
    EtchedLowVoltageWiring(new ModSimpleBaseItem("EtchedLowVoltageWiring", ModTabList.ModCircuitsTab)),
    EtchedInsaneVoltageWiring(new ModSimpleBaseItem("EtchedInsaneVoltageWiring", ModTabList.ModCircuitsTab)),
    EtchedLudicrousVoltageWiring(new ModSimpleBaseItem("EtchedLudicrousVoltageWiring", ModTabList.ModCircuitsTab)),
    ExtruderShapeBoat(new ModSimpleBaseItem("ExtruderShapeBoat", ModTabList.ModShapesTab)),
    FieryBloodDrop(new ModSimpleBaseItem("FieryBloodDrop", ModTabList.ModThaumcraftTab)),
    GeneticCircuit(new ModSimpleBaseItem("GeneticCircuit", ModTabList.ModCircuitsTab)),
    GlowingMarshmallow(new ModSimpleBaseItem("GlowingMarshmallow", ModTabList.ModThaumcraftTab)),
    GoldCoreChip(new ModSimpleBaseItem("GoldCoreChip", ModTabList.ModCircuitsTab)),
    GoldWandCap(new ModSimpleBaseItem("GoldWandCap", ModTabList.ModThaumcraftTab)),
    HeavyDutyAlloyIngotT4(new ModSimpleBaseItem("HeavyDutyAlloyIngotT4", ModTabList.ModGenericTab)),
    HeavyDutyAlloyIngotT5(new ModSimpleBaseItem("HeavyDutyAlloyIngotT5", ModTabList.ModGenericTab)),
    HeavyDutyAlloyIngotT6(new ModSimpleBaseItem("HeavyDutyAlloyIngotT6", ModTabList.ModGenericTab)),
    HeavyDutyAlloyIngotT7(new ModSimpleBaseItem("HeavyDutyAlloyIngotT7", ModTabList.ModGenericTab)),
    HeavyDutyAlloyIngotT8(new ModSimpleBaseItem("HeavyDutyAlloyIngotT8", ModTabList.ModGenericTab)),
    HeavyDutyAlloyIngotT9(new ModSimpleBaseItem("HeavyDutyAlloyIngotT9", ModTabList.ModGenericTab)),
    HighEnergyCircuitParts(new ModSimpleBaseItem("HighEnergyCircuitParts", ModTabList.ModCircuitsTab)),
    HighEnergyFlowCircuit(new ModSimpleBaseItem("HighEnergyFlowCircuit", ModTabList.ModCircuitsTab)),
    IchoriumCap(new ModSimpleBaseItem("IchoriumCap", ModTabList.ModThaumcraftTab)),
    InfernalBrick(new ModSimpleBaseItem("InfernalBrick", ModTabList.ModGenericTab)),
    IridiumItemCasing(new ModSimpleBaseItem("IridiumItemCasing", ModTabList.ModGenericTab)),
    IridiumBars(new ModSimpleBaseItem("IridiumBars", ModTabList.ModGenericTab)),
    IridiumAlloyItemCasing(new ModSimpleBaseItem("IridiumAlloyItemCasing", ModTabList.ModGenericTab)),
    IrradiantReinforcedAluminiumPlate(new ModSimpleBaseItem("IrradiantReinforcedAluminiumPlate", ModTabList.ModGenericTab)),
    IrradiantReinforcedChromePlate(new ModSimpleBaseItem("IrradiantReinforcedChromePlate", ModTabList.ModGenericTab)),
    IrradiantReinforcedNaquadriaPlate(new ModSimpleBaseItem("IrradiantReinforcedNaquadriaPlate", ModTabList.ModGenericTab)),
    IrradiantReinforcedNeutroniumPlate(new ModSimpleBaseItem("IrradiantReinforcedNeutroniumPlate", ModTabList.ModGenericTab)),
    IrradiantReinforcedTitaniumPlate(new ModSimpleBaseItem("IrradiantReinforcedTitaniumPlate", ModTabList.ModGenericTab)),
    IrradiantReinforcedTungstenPlate(new ModSimpleBaseItem("IrradiantReinforcedTungstenPlate", ModTabList.ModGenericTab)),
    IrradiantReinforcedTungstenSteelPlate(new ModSimpleBaseItem("IrradiantReinforcedTungstenSteelPlate", ModTabList.ModGenericTab)),
    IronWandCap(new ModSimpleBaseItem("IronWandCap", ModTabList.ModThaumcraftTab)),
    HotNetherrackBrick(new ModSimpleBaseItem("HotNetherrackBrick", ModTabList.ModGenericTab)),
    LaserEmitter(new ModSimpleBaseItem("LaserEmitter", ModTabList.ModGenericTab)),
    LeadNickelPlate(new ModSimpleBaseItem("LeadNickelPlate", ModTabList.ModGenericTab)),
    LedoxDust(new ModSimpleBaseItem("LedoxDust", ModTabList.ModGenericTab)),
    LedoxIngot(new ModSimpleBaseItem("LedoxIngot", ModTabList.ModGenericTab)),
    LedoxColdIngot(new ModSimpleBaseItem("LedoxColdIngot", ModTabList.ModGenericTab)),
    LedoxPlate(new ModSimpleBaseItem("LedoxPlate", ModTabList.ModGenericTab)),
    LedoxDensePlate(new ModSimpleBaseItem("LedoxDensePlate", ModTabList.ModGenericTab)),
    LedoxCompressedPlate(new ModSimpleBaseItem("LedoxCompressedPlate", ModTabList.ModGenericTab)),
    LichBone(new ModSimpleBaseItem("LichBone", ModTabList.ModThaumcraftTab)),
    LichBoneChip(new ModSimpleBaseItem("LichBoneChip", ModTabList.ModThaumcraftTab)),
    LichBoneFragment(new ModSimpleBaseItem("LichBoneFragment", ModTabList.ModThaumcraftTab)),
    LogicProcessorItemGoldCore(new ModSimpleBaseItem("LogicProcessorItemGoldCore", ModTabList.ModCircuitsTab)),
    LightShaft(new ModSimpleBaseItem("LightShaft", ModTabList.ModGenericTab)),
    LightBinding(new ModSimpleBaseItem("LightBinding", ModTabList.ModGenericTab)),
    LightAxeHead(new ModSimpleBaseItem("LightAxeHead", ModTabList.ModGenericTab)),
    LightPickaxeHead(new ModSimpleBaseItem("LightPickaxeHead", ModTabList.ModGenericTab)),
    LightSwordBlade(new ModSimpleBaseItem("LightSwordBlade", ModTabList.ModGenericTab)),
    LongObsidianRod(new ModSimpleBaseItem("LongObsidianRod", ModTabList.ModGenericTab)),
    LongStoneRod(new ModSimpleBaseItem("LongStoneRod", ModTabList.ModGenericTab)),
    ManyullynPlate(new ModSimpleBaseItem("ManyullynPlate", ModTabList.ModGenericTab)),
    MarsStoneDust(new ModSimpleBaseItem("MarsStoneDust", ModTabList.ModGenericTab)),
    NanoCircuit(new ModSimpleBaseItem("NanoCircuit", ModTabList.ModCircuitsTab)),
    MalformedSlush(new ModSimpleBaseItem("MalformedSlush", ModTabList.ModThaumcraftTab)),
    Marshmallow(new ModSimpleBaseItem("Marshmallow", ModTabList.ModThaumcraftTab)),
    ManyullynCrystal(new ModSimpleBaseItem("ManyullynCrystal", ModTabList.ModGenericTab)),
    MarshmallowForm(new ModSimpleBaseItem("MarshmallowForm", ModTabList.ModThaumcraftTab)),
    MarshmallowFormMold(new ModSimpleBaseItem("MarshmallowFormMold", ModTabList.ModThaumcraftTab)),
    EngravedManyullynCrystalChip(new ModSimpleBaseItem("EngravedManyullynCrystalChip", ModTabList.ModCircuitsTab)),
    MeteoricIronString(new ModSimpleBaseItem("MeteoricIronString", ModTabList.ModGenericTab)),
    MoldChestplate(new ModSimpleBaseItem("MoldChestplate", ModTabList.ModMoldsTab)),
    MoldHelmet(new ModSimpleBaseItem("MoldHelmet", ModTabList.ModMoldsTab)),
    MoldLeggings(new ModSimpleBaseItem("MoldLeggings", ModTabList.ModMoldsTab)),
    MoldFromLeggings(new ModSimpleBaseItem("MoldFormLeggings", ModTabList.ModMoldsTab)),
    MoldFromHelmet(new ModSimpleBaseItem("MoldFormHelmet", ModTabList.ModMoldsTab)),
    MoldFromChestplate(new ModSimpleBaseItem("MoldFormChestplate", ModTabList.ModMoldsTab)),
    MoldFromBoots(new ModSimpleBaseItem("MoldFormBoots", ModTabList.ModMoldsTab)),
    MoldBoots(new ModSimpleBaseItem("MoldBoots", ModTabList.ModMoldsTab)),
    MoldFormAnvil(new ModSimpleBaseItem("MoldFormAnvil", ModTabList.ModMoldsTab)),
    MoldFormArrowHead(new ModSimpleBaseItem("MoldFormArrowHead", ModTabList.ModMoldsTab)),
    MoldFormBaguette(new ModSimpleBaseItem("MoldFormBaguette", ModTabList.ModMoldsTab)),
    MoldFormBall(new ModSimpleBaseItem("MoldFormBall", ModTabList.ModMoldsTab)),
    MoldFormBlock(new ModSimpleBaseItem("MoldFormBlock", ModTabList.ModMoldsTab)),
    MoldFormBottle(new ModSimpleBaseItem("MoldFormBottle", ModTabList.ModMoldsTab)),
    MoldFormBread(new ModSimpleBaseItem("MoldFormBread", ModTabList.ModMoldsTab)),
    MoldFormBuns(new ModSimpleBaseItem("MoldFormBuns", ModTabList.ModMoldsTab)),
    MoldFormCasing(new ModSimpleBaseItem("MoldFormCasing", ModTabList.ModMoldsTab)),
    MoldFormCoinage(new ModSimpleBaseItem("MoldFormCoinage", ModTabList.ModMoldsTab)),
    MoldFormCylinder(new ModSimpleBaseItem("MoldFormCylinder", ModTabList.ModMoldsTab)),
    MoldFormGear(new ModSimpleBaseItem("MoldFormGear", ModTabList.ModMoldsTab)),
    MoldFormIngot(new ModSimpleBaseItem("MoldFormIngot", ModTabList.ModMoldsTab)),
    MoldFormName(new ModSimpleBaseItem("MoldFormName", ModTabList.ModMoldsTab)),
    MoldFormNuggets(new ModSimpleBaseItem("MoldFormNuggets", ModTabList.ModMoldsTab)),
    MoldFormPlate(new ModSimpleBaseItem("MoldFormPlate", ModTabList.ModMoldsTab)),
    MoldFormSmallGear(new ModSimpleBaseItem("MoldFormSmallGear", ModTabList.ModMoldsTab)),
    MoonStoneDust(new ModSimpleBaseItem("MoonStoneDust", ModTabList.ModGenericTab)),
    MushroomPowder(new ModSimpleBaseItem("MushroomPowder", ModTabList.ModGenericTab)),
    MysteriousCrystal(new ModSimpleBaseItem("MysteriousCrystal", ModTabList.ModGenericTab)),
    MysteriousCrystalDust(new ModSimpleBaseItem("MysteriousCrystalDust", ModTabList.ModGenericTab)),
    MysteriousCrystalIngot(new ModSimpleBaseItem("MysteriousCrystalIngot", ModTabList.ModGenericTab)),
    MysteriousCrystalColdIngot(new ModSimpleBaseItem("MysteriousCrystalColdIngot", ModTabList.ModGenericTab)),
    MysteriousCrystalPlate(new ModSimpleBaseItem("MysteriousCrystalPlate", ModTabList.ModGenericTab)),
    MysteriousCrystalDensePlate(new ModSimpleBaseItem("MysteriousCrystalDensePlate", ModTabList.ModGenericTab)),
    MysteriousCrystalCompressedPlate(new ModSimpleBaseItem("MysteriousCrystalCompressedPlate", ModTabList.ModGenericTab)),
    MytrylCrystal(new ModSimpleBaseItem("MytrylCrystal", ModTabList.ModGenericTab)),
    MytrylDust(new ModSimpleBaseItem("MytrylDust", ModTabList.ModGenericTab)),
    MytrylIngot(new ModSimpleBaseItem("MytrylIngot", ModTabList.ModGenericTab)),
    MytrylHotIngot(new ModSimpleBaseItem("MytrylHotIngot", ModTabList.ModGenericTab)),
    MytrylPlate(new ModSimpleBaseItem("MytrylPlate", ModTabList.ModGenericTab)),
    MytrylDensePlate(new ModSimpleBaseItem("MytrylDensePlate", ModTabList.ModGenericTab)),
    MytrylCompressedPlate(new ModSimpleBaseItem("MytrylCompressedPlate", ModTabList.ModGenericTab)),
    NagaScaleChip(new ModSimpleBaseItem("NagaScaleChip", ModTabList.ModThaumcraftTab)),
    NagaScaleFragment(new ModSimpleBaseItem("NagaScaleFragment", ModTabList.ModThaumcraftTab)),
    NanoCrystal(new ModSimpleBaseItem("NanoCrystal", ModTabList.ModCircuitsTab)),
    NanoProcessorBoard(new ModSimpleBaseItem("NanoProcessorBoard", ModTabList.ModCircuitsTab)),
    NanoChestJetPack(new ModSimpleBaseItem("NanoChestJetPack", ModTabList.ModGenericTab)),
    NanoPlatedLeggings(new ModSimpleBaseItem("NanoPlatedLeggings", ModTabList.ModGenericTab)),
    NanoRubberBoots(new ModSimpleBaseItem("NanoRubberBoots", ModTabList.ModGenericTab)),
    NanoScubaHelmet(new ModSimpleBaseItem("NanoScubaHelmet", ModTabList.ModGenericTab)),
    NaquadriaIronPlate(new ModSimpleBaseItem("NaquadriaIronPlate", ModTabList.ModGenericTab)),
    NeutroniumBars(new ModSimpleBaseItem("NeutroniumBars", ModTabList.ModGenericTab)),
    NeutroniumItemCasing(new ModSimpleBaseItem("NeutroniumItemCasing", ModTabList.ModGenericTab)),
    NeutroniumIronPlate(new ModSimpleBaseItem("NeutroniumIronPlate", ModTabList.ModGenericTab)),
    NeutronReflectorParts(new ModSimpleBaseItem("NeutronReflectorParts", ModTabList.ModCircuitsTab)),
    Nothing(new ModSimpleBaseItem("Nothing", ModTabList.ModGenericTab)),
    PikoCircuit(new ModSimpleBaseItem("PikoCircuit", ModTabList.ModCircuitsTab)),
    PistonPlate(new ModSimpleBaseItem("PistonPlate", ModTabList.ModGenericTab)),
    PotassiumHydroxideDust(new ModSimpleBaseItem("PotassiumHydroxideDust", ModTabList.ModGenericTab)),
    PulsatingIronBars(new ModSimpleBaseItem("PulsatingIronBars", ModTabList.ModGenericTab)),
    PulsatingSpatialCoreChip(new ModSimpleBaseItem("PulsatingSpatialCoreChip", ModTabList.ModCircuitsTab)),
    OsmiumItemCasing(new ModSimpleBaseItem("OsmiumItemCasing", ModTabList.ModGenericTab)),
    OsmiumBars(new ModSimpleBaseItem("OsmiumBars", ModTabList.ModGenericTab)),
    QuantinumDust(new ModSimpleBaseItem("QuantinumDust", ModTabList.ModGenericTab)),
    QuantinumHotIngot(new ModSimpleBaseItem("QuantinumHotIngot", ModTabList.ModGenericTab)),
    QuantinumPlate(new ModSimpleBaseItem("QuantinumPlate", ModTabList.ModGenericTab)),
    QuantinumDensePlate(new ModSimpleBaseItem("QuantinumDensePlate", ModTabList.ModGenericTab)),
    QuantinumCompressedPlate(new ModSimpleBaseItem("QuantinumCompressedPlate", ModTabList.ModGenericTab)),
    QuantinumRod(new ModSimpleBaseItem("QuantinumRod", ModTabList.ModGenericTab)),
    QuantumCircuit(new ModSimpleBaseItem("QuantumCircuit", ModTabList.ModCircuitsTab)),
    QuantumCrystal(new ModSimpleBaseItem("QuantumCrystal", ModTabList.ModCircuitsTab)),
    QuantumPartBoots(new ModSimpleBaseItem("QuantumPartBoots", ModTabList.ModGenericTab)),
    QuantumPartChestplate(new ModSimpleBaseItem("QuantumPartChestplate", ModTabList.ModGenericTab)),
    QuantumPartHelmet(new ModSimpleBaseItem("QuantumPartHelmet", ModTabList.ModGenericTab)),
    QuantumPartHelmetEmpty(new ModSimpleBaseItem("QuantumPartHelmetEmpty", ModTabList.ModGenericTab)),
    QuantumPartLeggings(new ModSimpleBaseItem("QuantumPartLeggings", ModTabList.ModGenericTab)),
    QuantumProcessorBoard(new ModSimpleBaseItem("QuantumProcessorBoard", ModTabList.ModCircuitsTab)),
    RawBioFiber(new ModSimpleBaseItem("RawBioFiber", ModTabList.ModGenericTab)),
    RedstoneAlloyBars(new ModSimpleBaseItem("RedstoneAlloyBars", ModTabList.ModGenericTab)),
    ReinforcedGlassPlate(new ModSimpleBaseItem("ReinforcedGlassPlate", ModTabList.ModGenericTab)),
    ReinforcedGlassLense(new ModSimpleBaseItem("ReinforcedGlassLense", ModTabList.ModGenericTab)),
    ReinforcedIridiumDrillTip(new ModSimpleBaseItem("ReinforcedIridiumDrillTip", ModTabList.ModGenericTab)),
    ReinforcedAluminiumIronPlate(new ModSimpleBaseItem("ReinforcedAluminiumIronPlate", ModTabList.ModGenericTab)),
    ReinforcedChromeIronPlate(new ModSimpleBaseItem("ReinforcedChromeIronPlate", ModTabList.ModGenericTab)),
    ReinforcedNaquadriaIronPlate(new ModSimpleBaseItem("ReinforcedNaquadriaIronPlate", ModTabList.ModGenericTab)),
    ReinforcedNeutroniumIronPlate(new ModSimpleBaseItem("ReinforcedNeutroniumIronPlate", ModTabList.ModGenericTab)),
    ReinforcedTitaniumIronPlate(new ModSimpleBaseItem("ReinforcedTitaniumIronPlate", ModTabList.ModGenericTab)),
    ReinforcedTungstenIronPlate(new ModSimpleBaseItem("ReinforcedTungstenIronPlate", ModTabList.ModGenericTab)),
    ReinforcedTungstenSteelIronPlate(new ModSimpleBaseItem("ReinforcedTungstenSteelIronPlate", ModTabList.ModGenericTab)),
    SandStoneRod(new ModSimpleBaseItem("SandStoneRod", ModTabList.ModGenericTab)),
    SawBladeStone(new ModSimpleBaseItem("SawBladeStone", ModTabList.ModGenericTab)),
    SawBladeDiamond(new ModSimpleBaseItem("SawBladeDiamond", ModTabList.ModGenericTab)),
    SawBladeArdite(new ModSimpleBaseItem("SawBladeArdite", ModTabList.ModGenericTab)),
    SawBladeManyullyn(new ModSimpleBaseItem("SawBladeManyullyn", ModTabList.ModGenericTab)),
    SawBladeRuby(new ModSimpleBaseItem("SawBladeRuby", ModTabList.ModGenericTab)),
    SawBladeSapphire(new ModSimpleBaseItem("SawBladeSapphire", ModTabList.ModGenericTab)),
    SawBladePeridot(new ModSimpleBaseItem("SawBladePeridot", ModTabList.ModGenericTab)),
    ShapeAxeHead(new ModSimpleBaseItem("ShapeAxeHead", ModTabList.ModShapesTab)),
    ShapeBlock(new ModSimpleBaseItem("ShapeBlock", ModTabList.ModShapesTab)),
    ShapeBoat(new ModSimpleBaseItem("ShapeBoat", ModTabList.ModShapesTab)),
    ShapeBolt(new ModSimpleBaseItem("ShapeBolt", ModTabList.ModShapesTab)),
    ShapeBottle(new ModSimpleBaseItem("ShapeBottle", ModTabList.ModShapesTab)),
    ShapeCasing(new ModSimpleBaseItem("ShapeCasing", ModTabList.ModShapesTab)),
    ShapeCell(new ModSimpleBaseItem("ShapeCell", ModTabList.ModShapesTab)),
    ShapeFileHead(new ModSimpleBaseItem("ShapeFileHead", ModTabList.ModShapesTab)),
    ShapeGear(new ModSimpleBaseItem("ShapeGear", ModTabList.ModShapesTab)),
    ShapeHammerHead(new ModSimpleBaseItem("ShapeHammerHead", ModTabList.ModShapesTab)),
    ShapeHoeHead(new ModSimpleBaseItem("ShapeHoeHead", ModTabList.ModShapesTab)),
    ShapeHugePipe(new ModSimpleBaseItem("ShapeHugePipe", ModTabList.ModShapesTab)),
    ShapeIngot(new ModSimpleBaseItem("ShapeIngot", ModTabList.ModShapesTab)),
    ShapeLargePipe(new ModSimpleBaseItem("ShapeLargePipe", ModTabList.ModShapesTab)),
    ShapeNormalPipe(new ModSimpleBaseItem("ShapeNormalPipe", ModTabList.ModShapesTab)),
    ShapePickaxeHead(new ModSimpleBaseItem("ShapePickaxeHead", ModTabList.ModShapesTab)),
    ShapePlate(new ModSimpleBaseItem("ShapePlate", ModTabList.ModShapesTab)),
    ShapeRing(new ModSimpleBaseItem("ShapeRing", ModTabList.ModShapesTab)),
    ShapeRod(new ModSimpleBaseItem("ShapeRod", ModTabList.ModShapesTab)),
    ShapeSawBlade(new ModSimpleBaseItem("ShapeSawBlade", ModTabList.ModShapesTab)),
    ShapeShovelHead(new ModSimpleBaseItem("ShapeShovelHead", ModTabList.ModShapesTab)),
    ShapeSmallPipe(new ModSimpleBaseItem("ShapeSmallPipe", ModTabList.ModShapesTab)),
    ShapeSwordBlade(new ModSimpleBaseItem("ShapeSwordBlade", ModTabList.ModShapesTab)),
    ShapeTinyPipe(new ModSimpleBaseItem("ShapeTinyPipe", ModTabList.ModShapesTab)),
    ShapeWire(new ModSimpleBaseItem("ShapeWire", ModTabList.ModShapesTab)),
    SimpleCircuitBoard(new ModSimpleBaseItem("SimpleCircuitBoard", ModTabList.ModCircuitsTab)),
    SnowQueenBlood(new ModSimpleBaseItem("SnowQueenBlood", ModTabList.ModThaumcraftTab)),
    SnowQueenBloodDrop(new ModSimpleBaseItem("SnowQueenBloodDrop", ModTabList.ModThaumcraftTab)),
    SoulariumBars(new ModSimpleBaseItem("SoulariumBars", ModTabList.ModGenericTab)),
    StainlessSteelBars(new ModSimpleBaseItem("StainlessSteelBars", ModTabList.ModGenericTab)),
    StainlessSteelItemCasing(new ModSimpleBaseItem("StainlessSteelItemCasing", ModTabList.ModGenericTab)),
    SteelBars(new ModSimpleBaseItem("SteelBars", ModTabList.ModGenericTab)),
    StonePlate(new ModSimpleBaseItem("StonePlate", ModTabList.ModGenericTab)),
    TitaniumBars(new ModSimpleBaseItem("TitaniumBars", ModTabList.ModGenericTab)),
    TitaniumItemCasing(new ModSimpleBaseItem("TitaniumItemCasing", ModTabList.ModGenericTab)),
    TitaniumIronPlate(new ModSimpleBaseItem("TitaniumIronPlate", ModTabList.ModGenericTab)),
    TungstenBars(new ModSimpleBaseItem("TungstenBars", ModTabList.ModGenericTab)),
    TungstenItemCasing(new ModSimpleBaseItem("TungstenItemCasing", ModTabList.ModGenericTab)),
    TungstenIronPlate(new ModSimpleBaseItem("TungstenIronPlate", ModTabList.ModGenericTab)),
    TungstenSteelBars(new ModSimpleBaseItem("TungstenSteelBars", ModTabList.ModGenericTab)),
    TungstenSteelItemCasing(new ModSimpleBaseItem("TungstenSteelItemCasing", ModTabList.ModGenericTab)),
    TungstenSteeLIronPlate(new ModSimpleBaseItem("TungstenSteelIronPlate", ModTabList.ModGenericTab)),
    UncookedSlush(new ModSimpleBaseItem("UncookedSlush", ModTabList.ModThaumcraftTab)),
    UnfiredClayBrick(new ModSimpleBaseItem("UnfiredClayBrick", ModTabList.ModGenericTab)),
    UnfiredCokeOvenBrick(new ModSimpleBaseItem("UnfiredCokeOvenBrick", ModTabList.ModGenericTab)),
    UnfiredSearedBrick(new ModSimpleBaseItem("UnfiredSearedBrick", ModTabList.ModGenericTab)),
    UnfiredSlimeSoulBrick(new ModSimpleBaseItem("UnfiredSlimeSoulBrick", ModTabList.ModGenericTab)),
    VibrantAlloyBars(new ModSimpleBaseItem("VibrantAlloyBars", ModTabList.ModGenericTab)),
    VoidFoil(new ModSimpleBaseItem("VoidFoil", ModTabList.ModThaumcraftTab)),
    VoidPlate(new ModSimpleBaseItem("VoidPlate", ModTabList.ModThaumcraftTab)),
    VoidRing(new ModSimpleBaseItem("VoidRing", ModTabList.ModThaumcraftTab)),
    VoidRod(new ModSimpleBaseItem("VoidRod", ModTabList.ModThaumcraftTab)),
    WirelessTransmitter(new ModSimpleBaseItem("WirelessTransmitter", ModTabList.ModGenericTab)),
    WoodenBrickForm(new ModSimpleBaseItem("WoodenBrickForm", ModTabList.ModGenericTab)),

    // Do not delete this
    EndOfList(null);

    // ################################################################################
    public ModSimpleBaseItem Item;

    private ItemList(ModSimpleBaseItem pItem)
    {
        Item = pItem;
        if (Item != null) Item.setModIDName(Refstrings.MODID);
    }

    public static boolean AddToItemManager(ModItemManager pItemManager)
    {
        boolean tResult = true;
        for (ItemList il : ItemList.values())
        {
            if (il.Item != null) if (!pItemManager.AddItemToManagedRegistry(il.Item))
            {
                MainRegistry.Logger.error(String.format("Item [%s] failed to register", il.toString()));
                tResult = false;
            }
        }

        return tResult;
    }

    public ItemStack getIS()
    {
        return new ItemStack(Item.getConstructedItem(), 1);
    }

}
