//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 01:34:59 PM CEST 
//


package com.dreammaster.xsd_hazardousitems;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "HazardousItemList")
public class HazardousItems {
 
    @XmlElement(name = "Item")
    protected List<HazardousItems.HazardousItem> hazardousItem;
 
    public List<HazardousItems.HazardousItem> getHazardousItems() {
        if (hazardousItem == null)
                hazardousItem = new ArrayList<HazardousItems.HazardousItem>();
 
        return hazardousItem;
    }
   
    @XmlAccessorType(XmlAccessType.FIELD)  
    @XmlType
    public static class HazardousItem {
 
    	@XmlAttribute(name = "UnlocalizedName")
        public String unlocName;
        @XmlAttribute(name = "ExactNameMatch")
        protected boolean exactMatch;
       
        @XmlElement(name = "DamageEffect")
        protected List<HazardousItems.HazardousItem.ItmDamageEffect> damageEffect;
        @XmlElement(name = "PotionEffect")
        protected List<HazardousItems.HazardousItem.ItmPotionEffect> potionEffect;
 
 
 
        public String getUnlocName() {
            return unlocName;
        }
 
        public void setUnlocName(String value) {
            this.unlocName = value;
        }
 
        public boolean getExactMatch() {
            return exactMatch;
        }
 
        public void setExactMatch(boolean value) {
            this.exactMatch = value;
        }
 
        public List<HazardousItems.HazardousItem.ItmPotionEffect> getPotionEffects() {
            if (potionEffect == null) {
                potionEffect = new ArrayList<HazardousItems.HazardousItem.ItmPotionEffect>();
            }
            return this.potionEffect;
        }
 
        public List<HazardousItems.HazardousItem.ItmDamageEffect> getDamageEffects() {
            if (damageEffect == null) {
                damageEffect = new ArrayList<HazardousItems.HazardousItem.ItmDamageEffect>();
            }
            return this.damageEffect;
        }
   
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType
        public static class ItmDamageEffect {
 
            @XmlAttribute(name = "Source")
            protected String damageSource;
            @XmlAttribute(name = "Amount")
            protected Float amount;
 
            public String getDamageSource() {
                return damageSource;
            }
 
            public void setDamageSource(String value) {
                this.damageSource = value;
            }
 
            public Float getAmount() {
                return amount;
            }
 
            public void setAmount(Float value) {
                this.amount = value;
            }
 
        }
 
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType
        public static class ItmPotionEffect {
 
            @XmlAttribute(name = "PotionID")
            protected Integer id;
            @XmlAttribute(name = "TickDuration")
            protected Integer duration;
            @XmlAttribute(name = "Level")
            protected Integer level;
 
            public Integer getId() {
                return id;
            }
 
            public void setId(Integer value) {
                this.id = value;
            }
 
            public Integer getDuration() {
                return duration;
            }
 
            public void setDuration(Integer value) {
                this.duration = value;
            }
 
            public Integer getLevel() {
                return level;
            }
 
            public void setLevel(Integer value) {
                this.level = value;
            }
        }
    }
}
