// --- Created by DreamMasterXXL ---
// --- Adding Recipes ---

// --- Infinity Booster Card 
mods.avaritia.ExtremeCrafting.addShaped(<ae2wct:infinityBoosterCard>, [
[<appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>],
[<appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:6>, <Avaritia:Resource:4>, <Avaritia:Resource:6>, <appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:6>, <Avaritia:Resource:4>, <Avaritia:Resource:6>, <appliedenergistics2:item.ItemMultiMaterial:42>],
[<appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:4>, <Avaritia:Resource:5>, <Avaritia:Resource:4>, <appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:4>, <Avaritia:Resource:5>, <Avaritia:Resource:4>, <appliedenergistics2:item.ItemMultiMaterial:42>],
[<appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:6>, <Avaritia:Resource:4>, <Avaritia:Resource:6>, <appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:6>, <Avaritia:Resource:4>, <Avaritia:Resource:6>, <appliedenergistics2:item.ItemMultiMaterial:42>],
[<appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>],
[<appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:6>, <Avaritia:Resource:4>, <Avaritia:Resource:6>, <appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:6>, <Avaritia:Resource:4>, <Avaritia:Resource:6>, <appliedenergistics2:item.ItemMultiMaterial:42>],
[<appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:4>, <Avaritia:Resource:5>, <Avaritia:Resource:4>, <appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:4>, <Avaritia:Resource:5>, <Avaritia:Resource:4>, <appliedenergistics2:item.ItemMultiMaterial:42>],
[<appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:6>, <Avaritia:Resource:4>, <Avaritia:Resource:6>, <appliedenergistics2:item.ItemMultiMaterial:42>, <Avaritia:Resource:6>, <Avaritia:Resource:4>, <Avaritia:Resource:6>, <appliedenergistics2:item.ItemMultiMaterial:42>],
[<appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>, <appliedenergistics2:item.ItemMultiMaterial:42>]]);